rem for western
copy %SystemRoot%\fonts\verdana.ttf .
copy %SystemRoot%\fonts\tahoma.ttf .
rem for symbol
copy %SystemRoot%\fonts\symbol.ttf .
rem for Chinese
copy %SystemRoot%\fonts\msyh.ttc .
copy %SystemRoot%\fonts\simsun.ttc .
copy %SystemRoot%\fonts\simkai.ttf .
copy %SystemRoot%\fonts\simfang.ttf .
